#!/bin/bash
echo "  "
echo "  "
echo "  "
echo "  "
firmware=$(sw_vers -productVersion) 
echo "💖系统版本:iOS $firmware"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "  "
echo "1.恢复系统原机盲文字体"
echo "  "
#iOS11
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 11.* ]]; then
     echo "正在还原原版盲文字体..."
     cp -a /var/mobile/SFonts/bak/iOS11-12/* /System/Library/Fonts/Core

fi
#iOS12
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 12.* ]]; then
     echo "正在还原原版盲文字体..."
     cp -a /var/mobile/SFonts/bak/iOS11-12/* /System/Library/Fonts/Core
fi

#iOS13
firmware=$(sw_vers -productVersion)
if  [[ $firmware == 13.* ]]; then
     echo "正在还原原版盲文字体..."
     cp -a /var/mobile/SFonts/bak/iOS13/* /System/Library/Fonts/Core
fi

rm -rf /var/mobile/SFonts
echo "2.系统盲文恢复成功"
echo "  "
echo "  "
echo "  "
echo "  "
echo "盲文字体by-kupord"
echo "  "
echo "  "
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
